name: mumshad_s_application5
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.9
  flutter_login_facebook: ^1.9.0
  google_sign_in: ^6.1.0
  intl: ^0.19.0
  permission_handler: ^10.1.0
  images_picker: ^1.2.11
  sqflite: ^2.3.0
  get_storage: ^2.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
